### ISSUE TITLE
3.2 upgrade references 3.0.z incorrectly

### ISSUE THREAD

**Issue by afcollins** [quay/quay-docs#30]
More so a question whether the documentation is correct.
It makes more sense that I am upgrading to 3.2, so I would bring up 3.2.z clair and builder versions, not the old 3.0.z version.

Line in question: https://github.com/quay/quay-docs/blame/3.2-release/modules/proc_upgrade_v3.adoc#L165

Currently reads (in 3.2.1 documentation): "Start v3.0.z versions ..."

I think it should read: "Start v3.2.1 versions ..."

**Comment by BillDett** [comment]
good catch- thanks!
