### ISSUE TITLE
Setting up clair security scanning

### ISSUE THREAD

**Issue by fsbano** [quay/quay-docs#78]
Hi good morning

I'm using quay (community) and now I'm trying to download the image of the clair with the command 'docker pull quay.io/redhat/clair-jwt:v3.3.0' but I'm getting the following error below

fsbano @ argon ~% docker login quay.io
Username: fsbano
Password:
Login successful
fsbano @ argon ~% docker pull quay.io/redhat/clair-jwt:v3.3.0
Daemon error response: unauthorized: access to the requested resource is not authorized
fsbano @ argon ~%

Best regards,
Fábio Sbano

**Comment by thomasmckay** [comment]
Please use the quay-sig email list for questions, not github issues. https://groups.google.com/g/quay-sig

See product documentation for Red Hat images. For upstream releases, see the quay-sig list for release announcements. The upstream pre-built images are in quay.io/projectquay repos.

Thanks!
