### ISSUE TITLE
Quay geo replication upgrade steps in wrong place

### ISSUE THREAD

**Issue by shane-snyder** [quay/quay-docs#920]
The Quay georeplication upgrade steps are under the quay bridge operator upgrade panel. These should be under the Quay operator upgrade panel.

https://access.redhat.com/documentation/en-us/red_hat_quay/3/html-single/upgrade_red_hat_quay/index#upgrading-geo-repl-quay-operator

**Comment by BillDett** [comment]
Thanks for reporting! Added to our backlog- https://issues.redhat.com/browse/PROJQUAY-6875
